### ISSUE TITLE
revision IEEE830

### ISSUE THREAD

**Issue by JuanPa-Portugal** [JuanPa-Portugal/Proyecto_MountainHike-2023#1]
1. Revisar documentación IEEE830 si está completa 
2. fijar los puntos faltantes en borrador si hubiera y ampliar en la sigute reu

[Grupo 34 - MOUNTAIN HIKE CÓRDOBA ieee-830.docx](https://github.com/JuanPa-Portugal/Proyecto_MountainHike-2023/files/11194788/Grupo.34.-.MOUNTAIN.HIKE.CORDOBA.ieee-830.docx)

**Comment by SoledadPeralta** [comment]
Trabajando el documento aquí: https://docs.google.com/document/d/1_GJW5Hu5mGeeLj31VQh4LchG930-maXrqmoY1hPDxlY/edit
