### ISSUE TITLE
#US10 Como administrador quiero que una vez realizada la compra se le muestre al usuario una lista de recomendaciones y agradecimientos

### ISSUE THREAD

**Issue by florenciamorisse** [JuanPa-Portugal/Proyecto_MountainHike-2023#10]
El administrador quiere que apenas realizada la compra aparezca un mensaje con un agradecimiento  y una lista de recomendaciones:
-llevar agua
- llevar comida
- ponerse protector solar y llevar para reforzar
- ponerse repelente y llevar para reforzar
- llevar gorra, anteojos de sol, abrigo liviano
- No dejar basura en el cerro durante el recorrido

👉 #17

**Comment by SoledadPeralta** [comment]
No se implementa
