### ISSUE TITLE
#US11 Como administrador quiero que una vez realizada la compra el usuario reciba un mail con el detalle de la compra

### ISSUE THREAD

**Issue by florenciamorisse** [JuanPa-Portugal/Proyecto_MountainHike-2023#11]
El administrador quiere que el usuario que haya contratado el servicio reciba un mail para agradecerle, darle transparencia, que quede un vínculo y que le de tranquilidad al cliente, a su vez desde el mismo mail podrá acceder a su dashboard para cambiar la fecha o camcelar el recorrido. También en el mismo figurará un descuento para futuras compras.
👉 #18 #19 #20 #21 #22

**Comment by SoledadPeralta** [comment]
No se implementa
