### ISSUE TITLE
#TK115 crear Cards de productos de compra

### ISSUE THREAD

**Issue by JuanPa-Portugal** [JuanPa-Portugal/Proyecto_MountainHike-2023#115]
👉 US #89 
- la card debe contener imagen previa
- titulo del producto
- descripcion
- badge (categoria del producto)
- badge (nivel de dificultad)
- precio
- boton call to action de compra
- boton mas detalles(redireccion a descripcion completa del producto)

**Comment by SoledadPeralta** [comment]
No llegamos a hacerlo para este proyecto
