### ISSUE TITLE
#US13 Como administrador quiero que el usuario tenga un dashboard personal para fomentar la fidelidad

### ISSUE THREAD

**Issue by florenciamorisse** [JuanPa-Portugal/Proyecto_MountainHike-2023#13]
El administrador quiere brindar al usuario un dashboard desde el que pueda  ver los recorrido contratados con anterioridad y desde donde pueda cambiar o cancelar los servicios que tiene contratados que aún no realizó. Esto crea un espacio privado para el usuario.
👉 #25 #26

**Comment by SoledadPeralta** [comment]
Se completa una parte
