### ISSUE TITLE
Semantica , Responsividad

### ISSUE THREAD

**Issue by JuanPa-Portugal** [JuanPa-Portugal/Proyecto_MountainHike-2023#2]
1. Revisar la estructura web Semántica, responsive (RWD)
2. Que mejoras se puede realizar
3. implementar bosquejos de diseño del nuevo modulo e-commerce

**Comment by Claudio-Olivera** [comment]
Trabajando el documento aquí: https://docs.google.com/document/d/1Aph88KD3x1HY5W-68Z6WdjMaOtHWOaBXjAi2s8_wIkc/edit?usp=sharing

**Comment by JuanPa-Portugal** [comment]
Documento viendo semantica- respnsivac y mejoras:
https://docs.google.com/document/d/1NE5hFsqA11ZcDcWD01RSsa0GTOLE-uazvrzNJfeW_i4/edit
