### ISSUE TITLE
#US30 Como usuario, quiero que se puedan quitar productos/servicios del carrito de compra con un bóton, para evitar salir de la compra si quiero cancelar un producto o servicio

### ISSUE THREAD

**Issue by Claudio-Olivera** [JuanPa-Portugal/Proyecto_MountainHike-2023#30]
El usuario desea poder eliminar productos de su carrito de compra, eligiendo cual quitar, sin necesidad de cancelar toda la compra. Plantea la idea de colocar un botón para realizar dicha funcionalidad.

**Comment by SoledadPeralta** [comment]
No se implementa en este proyecto
