### ISSUE TITLE
#TK42 • Crear la logica necesaria para que el botón pueda realizar la eliminacion del producto o servicio.

### ISSUE THREAD

**Issue by Claudio-Olivera** [JuanPa-Portugal/Proyecto_MountainHike-2023#42]
Relacionada a la user story #30 

Una forma de realizarlo, puede ser eliminar con una función el index correspondiente a ese producto / servicio, al accionar el evento con la directiva (click) de Angular.

**Comment by SoledadPeralta** [comment]
No implementado
