### ISSUE TITLE
#US09 Como administrador quiero ofrecer un descuento o promoción para los usuarios que hayan realizado algún recorrido con nosotros

### ISSUE THREAD

**Issue by florenciamorisse** [JuanPa-Portugal/Proyecto_MountainHike-2023#9]
El administrador quiere ofrecer un descuento a los usuarios que ya contrataron el servicio, debe ser un código que se envía en el mail de confirmación de compra junto al agradecimiento, con una leyenda similar a "Seguí disfrutando de la naturaleza y aprovecha este descuento en tu próxima compra"
👉 #14 #15 #16

**Comment by SoledadPeralta** [comment]
No se implementa
