### ISSUE TITLE
#US99 Como usuario quiero que haya un botón de whatsapp para poder contactarme más fácilmente con un representante de ventas del sitio (RF)

### ISSUE THREAD

**Issue by JuanPa-Portugal** [JuanPa-Portugal/Proyecto_MountainHike-2023#99]
se desea implementar un boton de whatsapp que quede estatico en la parte inferior de la pagina que pueda perseguir el scroll, al hacer clik enviar a la app de Watshaap para hablar con un representante

👉 task de #105

**Comment by SoledadPeralta** [comment]
No se llega a implementar en este proyecto
